language: objective-c
install:
  - bundle install --path vendor/bundle
  - bundle exec itamae local roles/local.rb -y nodes/local.yml
script:
  - bundle exec rubocop
  - bundle exec yaml-lint
  - bundle exec rake spec
addons:
  ssh_known_hosts: github.com
