language: objective-c
# Work around https://github.com/travis-ci/travis-ci/issues/1588
before_install: echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - bundle install --path vendor/bundle
  - bundle exec itamae local roles/local.rb -y nodes/local.yml
script:
  - bundle exec rubocop
  - bundle exec yaml-lint nodes/
  - bundle exec rake spec
addons:
  ssh_known_hosts: github.com
