---
brew:
  enable_update: true
  enable_upgrade: true
  add_repositories:
    - homebrew/completions
    - caskroom/cask
    - caskroom/versions
  install_packages:
    - bash
    - bash-completion
    - brew-cask
    - curl
    - editorconfig
    - ghq
    - git
    - hub
    - jq
    - libyaml
    - openssl
    - peco
    - tig
    - tree
    - vim
    - wget
    # homebrew/completions
    - brew-cask-completion
    - bundler-completion
    - gem-completion
    - open-completion
    - vagrant-completion
  install_apps:
    - atom
    - dropbox
    - github-desktop
    - google-chrome
    - google-japanese-ime
    - java
    - kobito
    - skype
    - vagrant
    - vagrant-manager
    - virtualbox
    # caskroom/versions
    - firefox-ja


atom:
  install_packages:
    - ask-stack
    - autocomplete-paths
    - editorconfig
    - file-icons
    - highlight-selected
    - minimap
    - minimap-autohide
    - minimap-bookmarks
    - minimap-git-diff
    - minimap-highlight-selected
    - project-manager
    - regex-railroad-diagram
    - script
