---
brew:
  enable_update: true
  enable_upgrade: true
  add_repositories:
    - caskroom/cask
    - caskroom/versions
  install_packages:
    - bash
    - brew-cask
    - ghq
    - git
    - libyaml
    - openssl
    - peco
    - tree
  install_apps:
    - atom
    - dropbox
    - github-desktop
    - google-chrome
    - google-japanese-ime
    - java
    - kobito
    - skype
    - vagrant
    - vagrant-manager
    - virtualbox
    # caskroom/versions
    - firefox-ja
